export { getListSafe } from './get-list-safe'
export { getNumberFromRating } from './get-number-from-rating'
export { getYearFromDate } from './get-year-from-date'
export { getPersonGender } from './get-person-gender'
export { getValidateText } from './get-validate-text'
export { getCurrencyFromValue } from './get-currency-from-value'
export { getAgeFromBirthday } from './get-age-from-birthday'
export { getAgeOfDeath } from './get-age-of-death'
